<#
//File: apply-stignore.ps1
//Version: 1.1.0
//Updated: 2026-08-06
.SYNOPSIS
    Apply the standard .stignore rules to each recorded path from the scan manifest.

.DESCRIPTION
    Read the path manifest (JSON) generated by scan-stignore.ps1.
    For each recorded file: if it still exists, back it up and write the
    standard rules; if it no longer exists, remove it from the manifest.
    After updating the rule source, just rerun this script to sync all
    historical paths without rescanning.

.PARAMETER Source
    Standard rule source file path. Defaults to .stignore in the script dir.

.PARAMETER List
    Scan manifest path. Defaults to stignore-paths.json in the script dir.

.PARAMETER WhatIf
    Preview the replacements/cleanups via PowerShell WhatIf; no writes/deletes.

.PARAMETER Force
    Replace and clean without per-file confirmation.

.PARAMETER BackupList
    Back up the manifest to <name>.bak.<timestamp> before writing it back.

.EXAMPLE
    .\apply-stignore.ps1 -WhatIf
    Preview what would be replaced/cleaned.

.EXAMPLE
    .\apply-stignore.ps1 -Force
    Apply standard rules and clean stale paths without prompts.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [string]$Source = (Join-Path $PSScriptRoot '.stignore'),
    [string]$List = (Join-Path $PSScriptRoot 'stignore-paths.json'),
    [switch]$Force,
    [switch]$BackupList
)

$ErrorActionPreference = 'Stop'

function Safe-Pause {
    try {
        Write-Host "`nPress Enter to exit..." -ForegroundColor DarkGray
        $null = Read-Host
    } catch {
        Start-Sleep -Seconds 3
    }
}

trap {
    Write-Host "`n[FATAL] Script terminated: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor DarkGray
    Safe-Pause
    exit 1
}

if (-not (Test-Path $Source -PathType Leaf)) {
    Write-Error "Standard rule source not found: $Source"
    exit 1
}
if (-not (Test-Path $List -PathType Leaf)) {
    Write-Error "Manifest not found: $List (run .\scan-stignore.ps1 first)"
    exit 1
}

$sourceBytes = [System.IO.File]::ReadAllBytes($Source)
$sourceHash = (Get-FileHash -Path $Source -Algorithm SHA256).Hash
Write-Host "Standard rule source : $Source" -ForegroundColor Cyan
Write-Host "Source SHA256        : $sourceHash" -ForegroundColor DarkGray

$manifest = Get-Content -Path $List -Raw -Encoding UTF8 | ConvertFrom-Json
if ($null -eq $manifest -or $null -eq $manifest.files) {
    Write-Error "Manifest invalid or missing 'files': $List"
    exit 1
}
$records = [System.Collections.ArrayList]::new()
$kept = 0
$replaced = 0
$skippedSame = 0
$cleaned = 0
$errors = 0
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'

foreach ($item in $manifest.files) {
    $full = $item.path
    if ([string]::IsNullOrWhiteSpace($full)) { continue }

    if (-not (Test-Path $full -PathType Leaf)) {
        $doClean = $Force -or $PSCmdlet.ShouldProcess($full, 'clean stale path (remove from manifest)')
        if ($doClean) {
            if (-not $WhatIf) {
                Write-Host "  cleaned stale path: $full" -ForegroundColor DarkGray
            } else {
                Write-Host "  [preview] will clean stale path: $full" -ForegroundColor Yellow
            }
            $cleaned++
            continue
        }
        [void]$records.Add($item)
        continue
    }

    $kept++
    $fileHash = (Get-FileHash -Path $full -Algorithm SHA256).Hash
    if ($fileHash -eq $sourceHash) {
        Write-Host "  skipped (already identical): $full" -ForegroundColor DarkGray
        $skippedSame++
        [void]$records.Add($item)
        continue
    }

    $doReplace = $Force -or $PSCmdlet.ShouldProcess($full, 'replace with standard .stignore rules')
    if ($doReplace) {
        try {
            $bak = "$full.bak.$timestamp"
            Copy-Item -Path $full -Destination $bak -Force
            [System.IO.File]::WriteAllBytes($full, $sourceBytes)
            Write-Host "  replaced (backup: $bak): $full" -ForegroundColor Green
            $replaced++
            [void]$records.Add($item)
        } catch {
            Write-Warning "  failed $full : $($_.Exception.Message)"
            $errors++
            [void]$records.Add($item)
        }
    } else {
        [void]$records.Add($item)
    }
}

if (-not $WhatIf) {
    if ($BackupList) {
        $listBak = "$List.bak.$timestamp"
        Copy-Item -Path $List -Destination $listBak -Force
        Write-Host "Manifest backed up: $listBak" -ForegroundColor DarkGray
    }
    $newManifest = [pscustomobject]@{
        version   = $manifest.version
        scannedAt = $manifest.scannedAt
        updatedAt = (Get-Date).ToUniversalTime().ToString('o')
        count     = $records.Count
        roots     = $manifest.roots
        files     = $records
    }
    $json = $newManifest | ConvertTo-Json -Depth 4
    Set-Content -Path $List -Value $json -Encoding UTF8
}

Write-Host "`n==== Summary ====" -ForegroundColor Cyan
Write-Host "Original manifest items : $($manifest.files.Count)"
Write-Host "Still valid paths       : $kept"
Write-Host "Skipped (identical)     : $skippedSame"
Write-Host "Replaced / to replace   : $replaced"
Write-Host "Cleaned stale           : $cleaned"
Write-Host "Errors                  : $errors"
if ($WhatIfPreference) { Write-Host "(preview mode, no changes made)" -ForegroundColor Yellow }
Safe-Pause
