name: syncthing_ignore_gui
description: GUI tool to scan and apply Syncthing .stignore rules across all synced folders.
publish_to: 'none'
version: 1.20.2+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  crypto: ^3.0.0
  file_picker: ^13.1.0
  win32: ^6.4.0
  provider: ^6.1.2
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/.stignore
